In [1]:
import pandas as pd

In [2]:
train = pd.read_csv('../data/train.csv')

In [15]:
train['qid'].value_counts().max()

1

In [22]:
display(train.target.value_counts())
train.target.value_counts() / train.shape[0]

target
0    1225312
1      80810
Name: count, dtype: int64

target
0    0.93813
1    0.06187
Name: count, dtype: float64

In [46]:
pd.set_option('display.max_colwidth', None)
train[train.target == 0].sample(10).question_text.to_frame()

                                                                question_text
229441                    How have Mauri shoes become popular over the years?
292829           What is the real science research on creative visualization?
782151         How do ensure that the downtime data that we have is accurate?
293083                       How does music affect the individual as a whole?
1188296                              Why so many Indians on Quora hate China?
358582       Should one confess to someone even knowing they'll get rejected?
1110938                             What are reasons to keep nuclear weapons?
180032                                    Why doesn’t India recognize Kosovo?
142512   How does A college write a internship letter to a company or a bank?
33956                                        What is method for MCQ question?

In [45]:
train[train.target == 1].sample(10).question_text.to_frame()

                                                                                                                           question_text
233522                                                                                       Why are answers from Christians so useless?
1140152                                  Why do Indians boast about their great culture when they themselves have forgotten its essence?
1046362                                                                       Why don't the Greeks ally with the Kurds to attack Turkey?
1059668                                                                                                Do Indian girls like doggy-style?
430118                                                                                                  Why do people hate white people?
950225                                                                                               Is eating ice cream considered gay?
133552   Will Jehovah Witnesses, Mormons, Catholics and 7th Day Adventists make it to heaven even though they are in the books of cults?
456191                                                                                   Why do 'poor' people smoke shit expensive weed?
865243                                                                                    Why the f**k are u guys asking dumb questions?
1156599                        My religion demands that I castrate my dog myself. What tools and items do I need to safely castrate him?

In [30]:
test = pd.read_csv('../data/test.csv')
test

,qid,question_text
0,0000163e3ea7c7a74cd7,Why do so many women become so rude and arroga...
1,00002bd4fb5d505b9161,When should I apply for RV college of engineer...
2,00007756b4a147d2b0b3,What is it really like to be a nurse practitio...
3,000086e4b7e1c7146103,Who are entrepreneurs?
4,0000c4c3fbe8785a3090,Is education really making good people nowadays?
...,...,...
375801,ffff7fa746bd6d6197a9,How many countries listed in gold import in in...
375802,ffffa1be31c43046ab6b,Is there an alternative to dresses on formal p...
375803,ffffae173b6ca6bfa563,Where I can find best friendship quotes in Tel...
375804,ffffb1f7f1a008620287,What are the causes of refraction of light?
375805,fffff85473f4699474b0,Climate change is a worrying topic. How much t...

In [31]:
pd.read_csv('../data/sample_submission.csv')

                         qid  prediction
0       0000163e3ea7c7a74cd7           0
1       00002bd4fb5d505b9161           0
2       00007756b4a147d2b0b3           0
3       000086e4b7e1c7146103           0
4       0000c4c3fbe8785a3090           0
...                      ...         ...
375801  ffff7fa746bd6d6197a9           0
375802  ffffa1be31c43046ab6b           0
375803  ffffae173b6ca6bfa563           0
375804  ffffb1f7f1a008620287           0
375805  fffff85473f4699474b0           0

[375806 rows x 2 columns]